export { default as LoginPage } from './LoginPage'
export { default as RegisterPage } from './RegisterPage'
export { default as ProfilePage } from './ProfilePage'

// 学生相关页面
export { default as CoursesPage } from './student/CoursesPage'
export { default as CourseBrowsePage } from './student/CourseBrowsePage'
export { default as AssignmentsPage } from './student/AssignmentsPage'
export { default as AssignmentDetailPage } from './student/AssignmentDetailPage'
export { default as ExamsPage } from './student/ExamsPage'
export { default as ExamDetailPage } from './student/ExamDetailPage'
export { default as TakeExamPage } from './student/TakeExamPage'
export { default as CourseDetailPage } from './student/CourseDetailPage'
export { default as LiveClassesPage } from './student/LiveClassesPage'
export { default as SchedulePage } from './student/SchedulePage'
export { default as MessagesPage } from './student/MessagesPage'
export { default as WatchLivePage } from './student/WatchLivePage'
export { default as DiscussionsPage } from './student/DiscussionsPage'
export { default as DiscussionDetailPage } from './student/DiscussionDetailPage'

// 教师相关页面
export { default as TeacherCoursesPage } from './teacher/CoursesPage'
export { default as StudentsPage } from './teacher/StudentsPage'
export { default as TeacherAssignmentsPage } from './teacher/AssignmentsPage'
export { default as TeacherExamsPage } from './teacher/ExamsPage'
export { default as TeacherLiveClassesPage } from './teacher/LiveClassesPage'
export { default as AnalyticsPage } from './teacher/AnalyticsPage'
export { default as LiveManagementPage } from './teacher/LiveManagementPage'
export { default as LiveStreamPage } from './teacher/LiveStreamPage'

// 教师子页面
export { default as CreateCoursePage } from './teacher/courses/CreateCoursePage'
export { default as CourseEditPage } from './teacher/courses/CourseEditPage'
export { default as CourseMaterialsPage } from './teacher/courses/CourseMaterialsPage'
export { default as TeacherCourseViewPage } from './teacher/courses/TeacherCourseViewPage'
export { default as AssignmentsListPage } from './teacher/assignments/AssignmentsListPage'
export { default as CreateAssignmentPage } from './teacher/assignments/CreateAssignmentPage'
export { default as GradingPage } from './teacher/assignments/GradingPage'
export { default as ExamsListPage } from './teacher/exams/ExamsListPage'
export { default as CreateExamPage } from './teacher/exams/CreateExamPage'
export { default as ExamResultsPage } from './teacher/exams/ExamResultsPage'
export { default as EditExamPage } from './teacher/exams/EditExamPage'
export { default as SubmissionDetailPage } from './teacher/exams/SubmissionDetailPage'

// 管理员相关页面
export { default as UsersPage } from './admin/UsersPage'
export { default as AdminCoursesPage } from './admin/CoursesPage'
export { default as SystemPage } from './admin/SystemPage'
export { default as AdminAnalyticsPage } from './admin/AnalyticsPage'
